---

  - name: Copy a "sudoers" file on the remote machine for editing
    ansible.builtin.copy:
      src: main.js
      dest: /main.js
      remote_src: yes

  - name: start app
    register: npm_finished
    command: pm2 /main.js
    ignore_errors: yes

  # - name: run backend
  #   pm2:
  #     script: /main.js
  #     state: started
        # npm install
        # pm2 stop default
        # pm2 start npm -- start
          # - name: deploy backend
  #   copy: src=main.js dest=/
    # when: "{{ inventory_hostname == 'web' }}"
