---
  - name: create backend directory
    become: yes
    file:
      path: ~/backend
      state: directory
      mode: 0755

  - name: copy backend files
    become: yes
    copy:
      src: ~/project/artifact.tar.gz
      dest: ~/backend/artifact.tar.gz

  - name: unpack backend files
    become: yes
    shell: |
      cd ~/backend
      tar -vxf artifact.tar.gz
      rm -f artifact.tar.gz
  - name: start app 
    become: yes
    shell: |
      cd ~/backend
      npm install
      pm2 stop default
      pm2 start npm -- start
      cd dist
      pm2 start main.js --update-env
  # - name: Copy a "sudoers" file on the remote machine for editing
  #   ansible.builtin.copy:
  #     src: main.js
  #     dest: /main.js
  #     remote_src: yes

  # - name: start app
  #   register: npm_finished
  #   command: pm2 /main.js
  #   ignore_errors: yes

  # # - name: run backend
  #   pm2:
  #     script: /main.js
  #     state: started
        # npm install
        # pm2 stop default
        # pm2 start npm -- start
          # - name: deploy backend
  #   copy: src=main.js dest=/
    # when: "{{ inventory_hostname == 'web' }}"
