---

  - name: "install nodejs and npm."
    apt:
      pkg: 
      - nodejs
      - npm
      update_cache: yes
  - name: "install pm2"
    npm:
      name: pm2
      global: yes
      state: present